#!/usr/bin/env python3

import argparse
import difflib
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent.parent
SOURCE_PATH = ROOT_DIR / "external_converters" / "zigbeehive-watermeter.mjs"
TARGET_PATH = ROOT_DIR / "external_converters" / "external_converters.commonjs.js"
GENERATED_START = "// BEGIN GENERATED WATERMETER CONVERTER"
GENERATED_END = "// END GENERATED WATERMETER CONVERTER"


def render_generated_block(source: str) -> str:
    lines = source.splitlines()
    body_lines = [
        line
        for line in lines
        if not line.startswith("import ")
        and line not in ("const e = exposes.presets;", "const ea = exposes.access;")
    ]
    body = "\n".join(body_lines).strip()
    body = body.replace("fz.battery", "fromZigbee_1.battery")
    body = body.replace("export default {", "const waterMeter = {")

    if "export default" in body or "fz." in body:
        raise ValueError("Unsupported ESM syntax remains in generated CommonJS block")

    return (
        f"{GENERATED_START}\n"
        "// Generated by tools/sync_watermeter_converter.py. Do not edit this block.\n"
        f"{body}\n"
        f"{GENERATED_END}"
    )


def update_target(target: str, generated_block: str) -> str:
    start = target.find(GENERATED_START)
    end = target.find(GENERATED_END)
    if start < 0 or end < 0 or end < start:
        raise ValueError("Generated converter markers are missing or invalid")

    end += len(GENERATED_END)
    return target[:start] + generated_block + target[end:]


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize the CommonJS WaterMeter converter")
    parser.add_argument("--check", action="store_true", help="Fail if the generated block is out of date")
    args = parser.parse_args()

    current = TARGET_PATH.read_text(encoding="utf-8")
    generated = render_generated_block(SOURCE_PATH.read_text(encoding="utf-8"))
    updated = update_target(current, generated)

    if updated == current:
        return 0

    if args.check:
        diff = difflib.unified_diff(
            current.splitlines(),
            updated.splitlines(),
            fromfile=str(TARGET_PATH),
            tofile=f"{TARGET_PATH} (generated)",
            lineterm="",
        )
        print("\n".join(diff))
        return 1

    TARGET_PATH.write_text(updated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
